### PR TITLE
Feat: add Google and Facebook login buttons

### LINKED ISSUE #27: Login > Facebook & Google
Implement login using Facebook and Google Accounts.

### PR DESCRIPTION
**Pull request by eng-somaia**
need to be edited when Firebase registration is done.

### CODE REVIEW

**Comment by eng-somaia** [comment]
@DhiaaAlshamy  Please let me know when you finish the registration so that I can make the required changes.

**Comment by FatimaAlmashhor** [comment]
@eng-somaia you can create `firebase.js `folder instead of put in the app

**Comment by MuhannedNoman** [comment]
This is an excellent work @eng-somaia can you please move the buttons to the login component and then merge. Also, remove the console logs :)

**Comment by eng-somaia** [comment]
> This is an excellent work @eng-somaia can you please move the buttons to the login component and then merge. Also, remove the console logs :)

Done.

**Pull request merged**
