### PR TITLE
Perf : Fix progress bar

### PR DESCRIPTION
**Pull request by FatimaAlmashhor**

### CODE REVIEW

**Comment by MuhannedNoman** [comment]
This looks good, but it took me a while to see the login button down there. 
image
Let's make it out standing a bit.

**Comment by FatimaAlmashhor** [comment]
Done

**Comment by MuhannedNoman** [comment]
This is what I get after logging in 
image

**Comment by FatimaAlmashhor** [comment]
I fixed this is in  #135

**Comment by MuhannedNoman** [comment]
> 
> 
> I fixed this is in #135

OK, once the desktop issue is fixed there it will be merged.

**Pull request merged**
