### PR TITLE
Fix : Fix go home bug

### PR DESCRIPTION
**Pull request by FatimaAlmashhor**

### CODE REVIEW

**Comment by MuhannedNoman** [comment]
After Login the modal doesn't disappear ?

**Comment by FatimaAlmashhor** [comment]
if you mean 'auto' ? No after you click out of it

**Comment by MuhannedNoman** [comment]
> 
> 
> if you mean 'auto' ? No after you click out of it

Can we make it go away automatically after the animation is done ?

**Comment by FatimaAlmashhor** [comment]
@@" i have did it like this but made big bug in self assessment

**Comment by MuhannedNoman** [comment]
> 
> 
> @@" i have did it like this but made big bug in self assessment

OK, if this is causing issue, let's make the user login before taking the test how a bout that ?

**Comment by FatimaAlmashhor** [comment]
is this PR not working or what ??! i think I did it like before with login message only ?

**Review by MuhannedNoman — APPROVED** [review]

**Pull request merged**
