### PR TITLE
Modal holder bug

### PR DESCRIPTION
**Pull request by eng-somaia**
login withgoogle error

### CODE REVIEW

**Comment by FatimaAlmashhor** [comment]
I did some fixing in #135 @eng-somaia

**Comment by eng-somaia** [comment]
> I did some fixing in #135 @eng-somaia

Different bug.

**Comment by MuhannedNoman** [comment]
Can you remove the effect off getting bigger from here as well as the nav
image
Also, those look off ? Can you fix it please and make them 2 again.
image

**Comment by MuhannedNoman** [comment]
Fixed here https://github.com/FatimaAlmashhor/capstone-project-exhale/pull/150

**Pull request closed without merging**
