### PR TITLE
Build: add tailwind

### PR DESCRIPTION
**Pull request by eng-somaia**
set up tailwind and try it with a simple h1.

### CODE REVIEW

**Comment by eng-somaia** [comment]
I forgot about the 5 files changes max.

**Review by FatimaAlmashhor — COMMENTED** [review]
@eng-somaia  thanks for your hard working

**Comment by eng-somaia** [comment]
> @eng-somaia thanks for your hard working

My pleasure.

**Review by DhiaaAlshamy — APPROVED** [review]
Approved!

**Review by FatimaAlmashhor — APPROVED** [review]

**Comment by eng-somaia** [comment]
@MuhannedNoman 
I finished working on Tailwind. Let me know what you think.

**Review by MuhannedNoman — COMMENTED** [review]
Once this runs locally, feel free to merge.

**Comment by eng-somaia** [comment]
> Once this runs locally, feel free to merge.

**Comment by eng-somaia** [comment]
Done

**Pull request closed without merging**
