### PR TITLE
Feat : Add ArticalCard component

### LINKED ISSUE #23: ArticleCard > Component
This will allow us to render an article card to the screen. 

Variants: 
Hover: 
image
 Normal: 
image

### PR DESCRIPTION
**Pull request by FatimaAlmashhor**

### CODE REVIEW

**Comment by MuhannedNoman** [comment]
This looks good, but remove the comments and let's have an image variable if it's there then render the other look. Otherwise, render this. Final note, let's change header to title explain it better.

**Comment by FatimaAlmashhor** [comment]
> This looks good, but remove the comments and let's have an image variable if it's there then render the other look. Otherwise, render this. Final note, let's change header to title explain it better.

  comments ??! and I think it is better this way without image . it going to be  unequal in size . What do you think?!

**Comment by MuhannedNoman** [comment]
> 
> 
> > This looks good, but remove the comments and let's have an image variable if it's there then render the other look. Otherwise, render this. Final note, let's change header to title explain it better.
> 
> comments ??! and I think it is better this way without image . it going to be unequal in size . What do you think?!

You have some comments on the import button. 
You can set a custom width and height to the image so that It will be always the same. Even if it's smaller the text won't go up.

**Comment by FatimaAlmashhor** [comment]
@MuhannedNoman how can I delete @eng-somaia commits for this branch ?

**Comment by MuhannedNoman** [comment]
> 
> 
> @MuhannedNoman how can I delete @eng-somaia commits for this branch ?

Not sure but you can use 
`git rebase -i <commitSHA>~1`
After you save the latest work of yours and go back to your commit.  
`6998fc1` this one I guess.

**Comment by FatimaAlmashhor** [comment]
@MuhannedNoman  i tried to fix it

**Comment by MuhannedNoman** [comment]
@FatimaAlmashhor can you just copy your code to another branch and merge. This have some unnecessary changes.

**Pull request closed without merging**
