### PR TITLE
Sgv components

### LINKED ISSUE #24: Images > SvgComponent
Add the Svg components to the project as a react component.

### PR DESCRIPTION
**Pull request by eng-somaia**

### CODE REVIEW

**Review by FatimaAlmashhor — COMMENTED** [review]
@eng-somaia could you please omit the width and height to let Mr. @MuhannedNoman  just merge this on , I will add it to the image component

**Review by FatimaAlmashhor — COMMENTED** [review]
@eng-somaia do you think the `width `should be 100% and the `height `is auto to let the Image component change the the `width `correctly ?!

**Comment by eng-somaia** [comment]
> @eng-somaia do you think the `width `should be 100% and the `height `is auto to let the Image component change the the `width `correctly ?!

Done.

**Review by FatimaAlmashhor — APPROVED** [review]

**Comment by eng-somaia** [comment]
@MuhannedNoman 
Is there any problem with this PR? Why hasn't it been merged yet?

**Pull request merged**
